# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-07 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=16, verbose_name='工号')),
                ('management_job', models.CharField(max_length=16, verbose_name='部门职位')),
                ('username', models.CharField(max_length=30, verbose_name='姓名')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='入职时间')),
                ('email', models.EmailField(default=None, max_length=32, verbose_name='邮箱')),
            ],
        ),
    ]
