# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-10 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_auto_20200109_1530'),
        ('user', '0003_user_isactive'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='management_job',
        ),
        migrations.AddField(
            model_name='management',
            name='dep_name',
            field=models.CharField(default='', max_length=16, null=True, verbose_name='部门名称'),
        ),
        migrations.AddField(
            model_name='management',
            name='img',
            field=models.CharField(default='', max_length=64, verbose_name='图片路径'),
        ),
        migrations.AddField(
            model_name='management',
            name='name',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='management',
            name='position',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.Position'),
        ),
        migrations.AddField(
            model_name='management',
            name='position_name',
            field=models.CharField(default='', max_length=16, null=True, verbose_name='部门职位'),
        ),
        migrations.AddField(
            model_name='management',
            name='power',
            field=models.CharField(default='', max_length=2, null=True, verbose_name='权限'),
        ),
        migrations.AddField(
            model_name='management',
            name='sex',
            field=models.CharField(default='男', max_length=2, null=True, verbose_name='男'),
        ),
        migrations.AddField(
            model_name='management',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AlterField(
            model_name='management',
            name='create_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='management',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='management',
            name='job_no',
            field=models.CharField(default='', max_length=16, null=True, verbose_name='工号'),
        ),
        migrations.AlterField(
            model_name='management',
            name='username',
            field=models.CharField(max_length=30, verbose_name='账号'),
        ),
    ]
