# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-13 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_auto_20200109_1530'),
        ('management', '0002_auto_20200110_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.Department'),
        ),
        migrations.AlterField(
            model_name='management',
            name='sex',
            field=models.CharField(default='', max_length=2, null=True, verbose_name='男'),
        ),
    ]
