# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-16 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('is_commen', models.BooleanField(default=True, verbose_name='是否正常')),
                ('is_absent', models.BooleanField(default=False, verbose_name='是否旷工')),
                ('is_leave', models.BooleanField(default=False, verbose_name='是否请假')),
                ('is_late', models.BooleanField(default=False, verbose_name='是否迟到')),
                ('is_leave_early', models.BooleanField(default=False, verbose_name='是否早退')),
                ('comment', models.CharField(default='', max_length=100, verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'timebook',
            },
        ),
    ]
