# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-16 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('timebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timebook',
            name='user',
        ),
        migrations.AddField(
            model_name='timebook',
            name='management',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Management'),
        ),
    ]
