# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-06 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='report_list',
            table='report_list',
        ),
    ]
