# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-13 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20200106_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_list',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
