# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-11 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200110_1926'),
        ('report', '0003_auto_20200111_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_list',
            name='management',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Management'),
        ),
        migrations.AlterField(
            model_name='report_list',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
