# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-07 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30, verbose_name='用户')),
                ('ip_adress', models.CharField(max_length=50, verbose_name='ip地址')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('clock_time', models.DateTimeField(auto_now=True, verbose_name='被锁时间')),
            ],
        ),
    ]
