# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-09 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_ipinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isActive',
            field=models.IntegerField(default=0, verbose_name='是否激活'),
        ),
    ]
