# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-08 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.CharField(default=None, max_length=64, verbose_name='部门描述'),
        ),
    ]
